import type { Metadata } from "next";
import SidebarNav from "@/components/navigation/sidebar-nav";
import { Separator } from "@/components/ui/separator";
import { usePathname } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
        <div className="hidden space-y-6 p-10 pb-16 md:block">
          <div className="space-y-0.5">
            <h2 className="text-2xl font-bold tracking-tight">
              VACTORY V4 - NEXT BACK OFFICE
            </h2>
            <p className="text-muted-foreground">Back office front</p>
          </div>
          <Separator className="my-6" />
          <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
            <aside className="-mx-4 lg:w-1/5">
              <SidebarNav />
            </aside>
            <div className="flex-1 lg:max-w-2xl">{children}</div>
          </div>
        </div>
  );
}
